Add retry in bash

diff --git a/chart/compass/charts/director/templates/external-certificate-rotation-job.yaml b/chart/compass/charts/director/templates/external-certificate-rotation-job.yaml
--- a/chart/compass/charts/director/templates/external-certificate-rotation-job.yaml
+++ b/chart/compass/charts/director/templates/external-certificate-rotation-job.yaml
@@ -2,9 +2,9 @@ apiVersion: batch/v1beta1
 kind: CronJob
 metadata:
   name: "{{ $.Chart.Name }}-external-certificate-rotation-job"
-  namespace: "compass-system" # TD: use chart variable
+  namespace: {{ $.Release.Namespace }}
 spec:
-  schedule: "{{ .Values.global.externalCertJob.schedule }}"
+  schedule: "{{ .Values.global.externalCertConfiguration.rotationCronjob.schedule }}"
   concurrencyPolicy: Forbid
   successfulJobsHistoryLimit: 5
   failedJobsHistoryLimit: 5
@@ -12,19 +12,20 @@ spec:
   jobTemplate:
     metadata:
       labels:
-        cronjob: {{ .Values.global.externalCertJob.name }}
+        cronjob: {{ .Values.global.externalCertConfiguration.rotationCronjob.name }}
     spec:
       template:
         metadata:
           labels:
-            cronjob: {{ .Values.global.externalCertJob.name }}
+            cronjob: {{ .Values.global.externalCertConfiguration.rotationCronjob.name }}
         spec:
           {{ if .Values.global.isLocalEnv }}
           hostAliases:
             - ip: {{ .Values.global.minikubeIP }}
               hostnames:
-                - "{{ .Values.global.externalServicesMock.certSecuredHost }}.{{ .Values.global.ingress.domainName }}" # TD: host?
+                - "{{ .Values.global.externalServicesMock.certSecuredHost }}.{{ .Values.global.ingress.domainName }}"
           {{ end }}
+          serviceAccountName: {{ $.Chart.Name }}-{{ .Values.global.externalCertConfiguration.rotationCronjob.name }}
           restartPolicy: Never
           containers:
           - name: certificate-rotation
@@ -34,9 +35,68 @@ spec:
               - bash
               - -c
               - |
+                RED='\033[0;31m'
+                GREEN='\033[0;32m'
+                YELLOW='\033[0;33m'
+                NC='\033[0m' # No Color
+
                 set -e
 
-                echo "Issuing token..."
+                function getClientCert() {
+                  echo -e "${YELLOW}Getting the certificate chain... ${NC}"
+                  CERT_CHAIN_PKCS7_RESP=$(curl -s -m 30 -X POST \
+                    "$CERT_SVC_URL" \
+                    -H "Authorization: Bearer $TOKEN" \
+                    -H 'Content-Type: application/json' \
+                    -H 'Accept: application/json' \
+                    -d "{
+                          \"certificate-signing-request\": {
+                              \"value\": $JSON_CSR,
+                              \"type\": \"pkcs10-pem\",
+                              \"validity\": {
+                                \"value\": $CERT_VALIDITY,
+                                \"type\": \"DAYS\"
+                            }
+                          }
+                        }")
+
+                  echo -e "${YELLOW}JSON-decoding client certificate chain... ${NC}"
+                  CERT_CHAIN_PKCS7=$(jq -r '.["certificate-response"]["value"]' <<< "$CERT_CHAIN_PKCS7_RESP")
+
+                  if [ "$CERT_CHAIN_PKCS7" == "null" ]
+                  then
+                    echo -e "${RED}Could not get certificate response. Reason: ${NC}"
+                    echo "$CERT_CHAIN_PKCS7_RESP"
+                    exit 1
+                  fi
+
+                  echo -e "${YELLOW}Extracting client certificate... ${NC}"
+                  openssl pkcs7 -print_certs -out /tmp/client-certificate_pkcs7.pem <<< "$CERT_CHAIN_PKCS7"
+                  openssl x509 -in /tmp/client-certificate_pkcs7.pem -out /tmp/client-certificate.pem
+                }
+
+                function confirmValidIssuerLocalityOrRetry() {
+                  for (( i = 0; i < "$CLIENT_CERT_RETRY_ATTEMPTS"; i++ )); do
+                    echo -e "${YELLOW}Checking issuer locality... ${NC}"
+                    ISSUER_LOCALITY=$(openssl x509 -in /tmp/client-certificate.pem -noout -text | grep "Issuer:" | awk '{print $3}' | cut -d '=' -f2 | sed 's/,$//g')
+                    if [[ "$ISSUER_LOCALITY" != "$EXPECTED_ISSUER_LOCALITY" ]]; then
+                      echo -e "${RED}The issuer locality of the client certificate didn't match the expected one. We expect \"$EXPECTED_ISSUER_LOCALITY\" but have: \"$ISSUER_LOCALITY\" ${NC}"
+                      echo -e "${YELLOW}[Retry $(($i+1))] Getting new client certificate... ${NC}"
+                      getClientCert # This will override the client certificate file content with the newly issued certificate
+                    else
+                      echo -e "${GREEN}Issuer locality of the client certificate is valid. Proceeding with the next steps... ${NC}"
+                      IS_CERT_ISSUER_LOCALITY_VALID=true
+                      break
+                    fi
+                  done
+
+                  if [[ $IS_CERT_ISSUER_LOCALITY_VALID == false ]]; then
+                    echo -e "${RED}Couldn't get the client certificate with valid issuer locality after $CLIENT_CERT_RETRY_ATTEMPTS attempts. Exiting... ${NC}"
+                    exit 1
+                  fi
+                }
+
+                echo -e "${YELLOW}Issuing token... ${NC}"
                 TOKEN=$(curl -s -m 30 -X POST \
                   "$CERT_SVC_TOKEN_URL/oauth/token" \
                   -H 'Content-Type: application/x-www-form-urlencoded' \
@@ -44,79 +104,103 @@ spec:
                   -d "grant_type=client_credentials&token_format=bearer&client_id=$CERT_SVC_CLIENT_ID&client_secret=$CERT_SVC_CLIENT_SECRET" \
                   | jq -r .access_token)
 
-                echo "Generating an encrypted private key..."
+                echo -e "${YELLOW}Generating an encrypted private key... ${NC}"
                 PASS_PHRASE=$(openssl rand -base64 32)
                 openssl genpkey -pass pass:"$PASS_PHRASE" -aes-256-cbc -algorithm RSA -pkeyopt rsa_keygen_bits:2048 -out /tmp/encrypted-private-key.pem
 
-                echo "Saving an unencrypted copy of the private key..."
-                openssl rsa -in /tmp/encrypted-private-key.pem -out /tmp/client-private-key.pem -passin pass:"$PASS_PHRASE"
-                #chmod 644 /tmp/client-private-key.pem TD: Proly not needed?
+                echo -e "${YELLOW}Saving an unencrypted copy of the private key... ${NC}" # Later we use it to create a k8s secret, currently k8s does not support loading encrypted private keys
+                openssl rsa -in /tmp/encrypted-private-key.pem -out /tmp/unencrypted-private-key.pem -passin pass:"$PASS_PHRASE"
 
-                echo "Creating a CSR in json..."
-                openssl req -new -sha256 -key /tmp/client-private-key.pem -passin pass:"$PASS_PHRASE" -out /tmp/my-csr.pem \
+                echo -e "${YELLOW}Creating a CSR in json... ${NC}"
+                openssl req -new -sha256 -key /tmp/encrypted-private-key.pem -passin pass:"$PASS_PHRASE" -out /tmp/my-csr.pem \
                    -subj '$CERT_SUBJECT_PATTERN'
                 JSON_CSR=$(jq -sR '.' /tmp/my-csr.pem)
 
-                CERT_VALIDITY=7
+                getClientCert
 
-                echo "Getting the certificate chain..."
-                CERT_CHAIN_PKCS7_RESP=$(curl -s -m 30 -X POST \
-                  "$CERT_SVC_URL" \
-                  -H "Authorization: Bearer $TOKEN" \
-                  -H 'Content-Type: application/json' \
-                  -H 'Accept: application/json' \
-                  -d "{
-                        \"certificate-signing-request\": {
-                            \"value\": $JSON_CSR,
-                            \"type\": \"pkcs10-pem\",
-                            \"validity\": {
-                              \"value\": $CERT_VALIDITY,
-                              \"type\": \"DAYS\"
-                            }
-                        }
-                    }")
+                confirmValidIssuerLocalityOrRetry
 
-                echo "JSON-decoding client certificate chain..."
-                CERT_CHAIN_PKCS7=$(jq -r '.["certificate-response"]["value"]' <<< "$CERT_CHAIN_PKCS7_RESP")
-                jq -r '.["certificate-response"]["value"]' my-client-certificate-chain-response.json > my-client-certificate_pkcs7.pem
-
-                if [ "$CERT_CHAIN_PKCS7" == "null" ]
-                then
-                  echo "Could not get certificate response. Reason:"
-                  echo "$CERT_CHAIN_PKCS7_RESP"
-                  exit 1
-                fi
-
-                echo "Extracting client certificate..."
-                openssl pkcs7 -print_certs -out client-certificate_pkcs7.pem <<< "$CERT_CHAIN_PKCS7"
-                openssl x509 -in client-certificate_pkcs7.pem -out /tmp/client-certificate.pem
-
-                echo "Client certificate secret creating..."
-                kubectl create secret tls external-client-certificate --namespace=compass-system --cert=/tmp/client-certificate.pem --key=/tmp/client-private-key.pem --save-config --dry-run=client -o yaml | kubectl apply -f -
+                echo -e "${YELLOW}Creating/Updating client certificate secret... ${NC}"
+                kubectl create secret tls external-client-certificate --namespace=compass-system --cert=/tmp/client-certificate.pem --key=/tmp/unencrypted-private-key.pem --save-config --dry-run=client -o yaml | kubectl apply -f -
 
                 set +e
             env:
               - name: CERT_SVC_URL
                 valueFrom:
                   secretKeyRef:
-                    name: {{ .Values.global.director.secrets.externalCertSvcSecret.name }}
-                    key: {{ .Values.global.director.secrets.externalCertSvcSecret.certSvcUrlKey }}
+                    name: {{ .Values.global.externalCertConfiguration.secrets.externalCertSvcSecret.name }}
+                    key: {{ .Values.global.externalCertConfiguration.secrets.externalCertSvcSecret.csrEndpointKey }}{{ .Values.global.externalCertConfiguration.certSvcApiPath }}
               - name: CERT_SUBJECT_PATTERN
-                value: {{ quote (printf .Values.global.mtlsClient.subjectPattern .Values.global.mtlsClient.locality .Values.global.mtlsClient.commonName) }}
-              - name: CERT_ISSUER_LOCALITY
-                value: {{ .Values.global.ordAggregator.accessStrategies.cmpMtls.issuerLocality }}
+                value: {{ printf .Values.global.externalCertConfiguration.subjectPattern .Values.global.externalCertConfiguration.locality .Values.global.externalCertConfiguration.commonName }}
+              - name: EXPECTED_ISSUER_LOCALITY
+                value: {{ .Values.global.externalCertConfiguration.issuerLocality }}
+              - name: CERT_VALIDITY
+                value: {{ .Values.global.externalCertConfiguration.rotationCronjob.certValidity | quote }}
+              - name: CLIENT_CERT_RETRY_ATTEMPTS
+                value: {{ .Values.global.externalCertConfiguration.rotationCronjob.clientCertRetryAttempts | quote }}
               - name: CERT_SVC_CLIENT_ID
                 valueFrom:
                   secretKeyRef:
-                    name: {{ .Values.global.director.secrets.externalCertSvcSecret.name }}
-                    key: {{ .Values.global.director.secrets.externalCertSvcSecret.clientIdKey }}
+                    name: {{ .Values.global.externalCertConfiguration.secrets.externalCertSvcSecret.name }}
+                    key: {{ .Values.global.externalCertConfiguration.secrets.externalCertSvcSecret.clientIdKey }}
               - name: CERT_SVC_CLIENT_SECRET
                 valueFrom:
                   secretKeyRef:
-                    name: {{ .Values.global.director.secrets.externalCertSvcSecret.name }}
-                    key: {{ .Values.global.director.secrets.externalCertSvcSecret.clientSecretKey }}
+                    name: {{ .Values.global.externalCertConfiguration.secrets.externalCertSvcSecret.name }}
+                    key: {{ .Values.global.externalCertConfiguration.secrets.externalCertSvcSecret.clientSecretKey }}
               - name: CERT_SVC_TOKEN_URL
                 valueFrom:
                   secretKeyRef:
-                    name: {{ .Values.global.director.secrets.externalCertSvcSecret.name }}
-                    key: {{ .Values.global.director.secrets.externalCertSvcSecret.oauthUrlKey }}
+                    name: {{ .Values.global.externalCertConfiguration.secrets.externalCertSvcSecret.name }}
+                    key: {{ .Values.global.externalCertConfiguration.secrets.externalCertSvcSecret.oauthUrlKey }}
+---
+apiVersion: v1
+kind: ServiceAccount
+metadata:
+  name: {{ $.Chart.Name }}-{{ .Values.global.externalCertConfiguration.rotationCronjob.name }}
+  namespace: {{ $.Release.Namespace }}
+  labels:
+    app: {{ $.Chart.Name }}
+    release: {{ $.Release.Name }}
+    helm.sh/chart: {{ $.Chart.Name }}-{{ $.Chart.Version | replace "+" "_" }}
+    app.kubernetes.io/name: {{ template "name" . }}
+    app.kubernetes.io/managed-by: {{ $.Release.Service }}
+    app.kubernetes.io/instance: {{ $.Release.Name }}
+---
+apiVersion: rbac.authorization.k8s.io/v1
+kind: Role
+metadata:
+  name: {{ $.Chart.Name }}-{{ .Values.global.externalCertConfiguration.rotationCronjob.name }}
+  namespace: {{ $.Release.Namespace }}
+  labels:
+    app: {{ $.Chart.Name }}
+    release: {{ $.Release.Name }}
+    helm.sh/chart: {{ $.Chart.Name }}-{{ $.Chart.Version | replace "+" "_" }}
+    app.kubernetes.io/name: {{ template "name" . }}
+    app.kubernetes.io/managed-by: {{ $.Release.Service }}
+    app.kubernetes.io/instance: {{ $.Release.Name }}
+rules:
+  - apiGroups: ["*"]
+    resources: ["secrets"]
+    verbs: ["get", "create", "update"]
+---
+kind: RoleBinding
+apiVersion: rbac.authorization.k8s.io/v1
+metadata:
+  name: {{ $.Chart.Name }}-{{ .Values.global.externalCertConfiguration.rotationCronjob.name }}
+  namespace: {{ $.Release.Namespace }}
+  labels:
+    app: {{ $.Chart.Name }}
+    release: {{ $.Release.Name }}
+    helm.sh/chart: {{ $.Chart.Name }}-{{ $.Chart.Version | replace "+" "_" }}
+    app.kubernetes.io/name: {{ template "name" . }}
+    app.kubernetes.io/managed-by: {{ $.Release.Service }}
+    app.kubernetes.io/instance: {{ $.Release.Name }}
+subjects:
+  - kind: ServiceAccount
+    name: {{ $.Chart.Name }}-{{ .Values.global.externalCertConfiguration.rotationCronjob.name }}
+    namespace: {{ $.Release.Namespace }}
+roleRef:
+  kind: Role
+  name: {{ $.Chart.Name }}-{{ .Values.global.externalCertConfiguration.rotationCronjob.name }}
+  apiGroup: rbac.authorization.k8s.io
